spring:
  cloud:
    stream:
      default:
        contentType: application/json
      bindings:
        myinput:
          destination: mygirlMessage #要和output的destination一致, 这样才能将队列和写入消息的exchange关联起来
          binder: local_rabbit
          group: mygirlMessageConsumers
        myoutput:
          destination: mygirlMessage
          binder: local_rabbit
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.12.12
                port: 5672
                username: guest
                password: guest
                virtual-host: /